name = "SphericalFunctions"
uuid = "af6d55de-b1f7-4743-b797-0829a72cf84e"
version = "3.0.0-dev"
authors = ["Michael Boyle <michael.oliver.boyle@gmail.com>"]

[workspace]
projects = ["benchmark", "docs", "test"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
GenericFFT = "a8297547-1b15-4a5a-a998-a2ac5f1cef28"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Quaternionic = "0756cd96-85bf-4b6f-a009-b5012ea7a443"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"

[extensions]
SphericalFunctionsChainRulesCoreExt = "ChainRulesCore"
SphericalFunctionsDoubleFloatsExt = "DoubleFloats"
SphericalFunctionsEnzymeCoreExt = "EnzymeCore"
SphericalFunctionsForwardDiffExt = "ForwardDiff"
SphericalFunctionsMooncakeExt = "Mooncake"
SphericalFunctionsReverseDiffExt = "ReverseDiff"

[compat]
ChainRulesCore = "1"
DoubleFloats = "1"
EnzymeCore = "0.8"
FFTW = "1.5"
FixedSizeArrays = "1.3"
ForwardDiff = "0.10, 1"
GenericFFT = "0.1"
LinearAlgebra = "1"
Mooncake = "0.5"
PrecompileTools = "1"
Quaternionic = "3, 4"
ReverseDiff = "1"
Serialization = "1"
StaticArrays = "1"
julia = "1.10"
