name = "Spherical"
uuid = "af6d55de-b1f7-4743-b797-0829a72cf84e"
authors = ["Michael Boyle <michael.oliver.boyle@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
