@doc raw"""
    golden_ratio_spiral_pixels(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels generated by the golden-ratio spiral.  Successive pixels
are separated by the azimuthal angle ``Δϕ = 2π(2-φ)``, and are uniformly distributed in
``\cos θ``.

This is a common angular pattern of phyllotaxis in plants, found in sunflowers, pine cones,
and artichokes, for example.  Wrapped around 𝕊², this is a very reasonable-looking
pixelization, with fairly uniform distance between neighbors, and approximate isotropy.  No
two pixels will share the same values of either ``θ`` or ``ϕ``.  Also note that no point is
present on either the North or South poles.

This is also known as the "Fibonacci sphere" or "Fibonacci lattice" — though he had nothing
to do with it; later authors pointed out relationships between his sequence and the golden
ratio.

The returned quantity is a vector of 2-SVectors providing the spherical coordinates of each
pixel.  See also [`golden_ratio_spiral_rotors`](@ref) for the corresponding `Rotor`s.
"""
function golden_ratio_spiral_pixels(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    let π = T(π), φ = T(MathConstants.φ)
        N = (ℓₘₐₓ+1)^2 - s^2
        # Note: the formula used here looks different from some sources,
        # but just represents spiraling in the opposite direction.
        Δϕ = 2π * (2 - φ)
        ϕ = (0:N-1) * Δϕ
        cosθ = LinRange{T}(1, -1, N+1)[begin:end-1] .- 1/T(N)
        [@SVector [acos(cosθ), ϕ] for (cosθ, ϕ) in zip(cosθ, ϕ)]
    end
end

@doc raw"""
    golden_ratio_spiral_rotors(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels generated by the golden-ratio spiral.

See [`golden_ratio_spiral_pixels`](@ref) for more detailed explanation.  The quantity
returned by this function is a vector of `Rotor`s providing each pixel.
"""
function golden_ratio_spiral_rotors(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    from_spherical_coordinates.(golden_ratio_spiral_pixels(s, ℓₘₐₓ, T))
end

@doc raw"""
    sorted_rings(s, ℓₘₐₓ, [T=Float64])

Compute locations of a series of rings labelled by ``j ∈ |s|:ℓₘₐₓ`` (analogous
to ``ℓ``), where each ring will contain ``k = 2j+1`` (analogous to ``m``) pixels distributed
evenly around the ring.  These rings are then sorted, so that the ring with the most pixels
(``j = ℓₘₐₓ``) is closest to the equator, and the next-largest ring is placed just above or
below the equator (depending on the sign of ``s``), the next just below or above, and so on.
This is generally a fairly good first guess when minimizing the condition number of matrices
used to solve for mode weights from function values.  In particular, I use this to
initialize the Minimal algorithm, which is then fed into an optimizer to fine-tune the
positions of the rings.

This function does not provide the individual pixels; it just provides the colatitude values
of the rings on which the pixels will be placed.  The pixels themselves are provided by
[`sorted_ring_pixels`](@ref).
"""
function sorted_rings(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    let πo2 = prevfloat(T(π)/2, s)
        sort(
            collect(LinRange{T}(0, π, 2+ℓₘₐₓ-abs(s)+1))[begin+1:end-1],
            lt=(x,y)->(abs(x-πo2)<abs(y-πo2)),
            rev=true
        )
    end
end


"""
    sorted_ring_pixels(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with ``(ℓₘₐₓ+1)²-s²`` pixels distributed in rings provided by
[`sorted_rings`](@ref); see that function's documentation for more description.

The returned quantity is a vector of 2-SVectors containing the spherical coordinates of each
pixel.  See also [`sorted_ring_rotors`](@ref) for the corresponding `Rotor`s.
"""
function sorted_ring_pixels(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    θrings = sorted_rings(s, ℓₘₐₓ, T)
    [
        @SVector [θ, ϕ]
        for (j,θ) ∈ zip(abs(s):ℓₘₐₓ, θrings)
        for ϕ ∈ LinRange{T}(0, 2T(π), 2j+2)[begin:end-1]
    ]
end

"""
    sorted_ring_rotors(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with ``(ℓₘₐₓ+1)²-s²`` pixels distributed in rings provided by
[`sorted_rings`](@ref); see that function's documentation for more description.

The returned quantity is a vector of `Rotor`s.  See also [`sorted_ring_rotors`](@ref) for
the corresponding spherical coordinates.
"""
function sorted_ring_rotors(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    from_spherical_coordinates.(sorted_ring_pixels(s, ℓₘₐₓ, T))
end

"""
    fejer1_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by Fejér's first
rule, using weights provided by [`fejer1`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
"""
function fejer1_rings(N, ::Type{T}=Float64) where T
    # Eq. (12) of Reinecke and Seljebotn
    let π = T(π)
        [(2n+1)*π/2N for n ∈ 0:N-1]
    end
end

"""
    fejer2_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by Fejér's second
rule, using weights provided by [`fejer2`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
"""
function fejer2_rings(N, ::Type{T}=Float64) where T
    # Eq. (13) of Reinecke and Seljebotn, with N adjusted to reflect actual number of elements
    let π = T(π)
        [n*π/(N+1) for n ∈ 1:N]
    end
end

"""
    clenshaw_curtis_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by the
Clenshaw-Curtis rule, using weights provided by [`clenshaw_curtis`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
"""
function clenshaw_curtis_rings(N, ::Type{T}=Float64) where T
    # Eq. (14) of Reinecke and Seljebotn, with N adjusted to reflect actual number of elements
    let π = T(π)
        [n*π/(N-1) for n ∈ 0:N-1]
    end
end

@doc raw"""
    driscoll_healy_pixels([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [DriscollHealy_1994](@citet) equiangular grid:

> Let ``f(θ, ϕ)`` be a band-limited function such that ``\hat{f}(l, m) = 0`` for ``l
> ≥ b``.  We sample the function at the equiangular grid of points ``(θ_i, ϕ_j)``,
> ``i = 0, \ldots, 2b-1``, ``j = 0, \ldots, 2b-1``, where ``θ_i = π i/2b`` and
> ``ϕ_j = π j/b``.

The returned quantity is a vector of 2-SVectors providing the spherical coordinates of each
pixel.  See also [`driscoll_healy_rotors`](@ref) for the corresponding `Rotor`s.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
function driscoll_healy_pixels(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    let π = T(π)
        b = ℓₘₐₓ + 1
        [
            @SVector [π*i/2b, π*j/b]
            for i ∈ 0:(2b-1)
            for j ∈ 0:(2b-1)
        ]
    end
end
driscoll_healy_pixels(ℓₘₐₓ, ::Type{T}=Float64) where T = driscoll_healy_pixels(0, ℓₘₐₓ, T)

@doc raw"""
    driscoll_healy_rotors(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [DriscollHealy_1994](@citet) equiangular grid.

See [`driscoll_healy_pixels`](@ref) for more detailed explanation.  The quantity returned by
this function is a vector of `Rotor`s providing each pixel.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
function driscoll_healy_rotors(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    from_spherical_coordinates.(driscoll_healy_pixels(s, ℓₘₐₓ, T))
end
driscoll_healy_rotors(ℓₘₐₓ, ::Type{T}=Float64) where T = driscoll_healy_rotors(0, ℓₘₐₓ, T)


@doc raw"""
    mcewen_wiaux_pixels([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [McEwenWiaux_2011](@citet) equiangular grid:

> We adopt an equiangular sampling of the sphere with sample positions given by ``θ_t =
> \frac{π(2t+1)}{2ℓ_{\max}-1}``, where ``t ∈ \{0, 1, \dotsc, ℓ_\mathrm{max}-1\}``
> and ``ϕ_p = \frac{2 π p}{2ℓ_\mathrm{max}-1}``, where ``p ∈ \{0, 1, \dotsc,
> 2ℓ_\mathrm{max}-2\}``.  In order to extend the ``θ`` domain to ``[0, 2π)`` we
> simply extend the domain of the ``θ`` index to include ``\{ℓ_\mathrm{max},
> ℓ_\mathrm{max}+1, \dotsc, 2ℓ_\mathrm{max}-1\}``.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
function mcewen_wiaux_pixels(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    let π = T(π)
        [
            @SVector [π*(2t+1) / (2ℓₘₐₓ - 1), 2π*p / (2ℓₘₐₓ - 1)]
            for t ∈ 0:(2ℓₘₐₓ - 1)
            for p ∈ 0:(2ℓₘₐₓ - 2)
        ]
    end
end
mcewen_wiaux_pixels(ℓₘₐₓ, ::Type{T}=Float64) where T = mcewen_wiaux_pixels(0, ℓₘₐₓ, T)

@doc raw"""
    mcewen_wiaux_rotors([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [McEwenWiaux_2011](@citet) equiangular grid.

See [`mcewen_wiaux_pixels`](@ref) for more detailed explanation.  The quantity returned by
this function is a vector of `Rotor`s providing each pixel.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
function mcewen_wiaux_rotors(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    from_spherical_coordinates.(mcewen_wiaux_pixels(s, ℓₘₐₓ, T))
end
mcewen_wiaux_rotors(ℓₘₐₓ, ::Type{T}=Float64) where T = mcewen_wiaux_rotors(0, ℓₘₐₓ, T)
