# Pixelizations of the sphere.
#
# The golden-ratio spiral, the Leja points and the sorted rings are sized by the spin weight
# `s` and the band limit `ℓₘₐₓ`, which may be integers or half-odd-integers, the latter
# passed as `Rational`s with denominator 2 or as `HalfOddInteger`s.  Each of the four
# functions that compute points — `golden_ratio_spiral_pixels`, `leja_pixels`,
# `sorted_rings` and `sorted_ring_pixels` — is a boundary method, typed `IndexArgument` on
# its indices, which does nothing but normalize the two with `unify_indices` and re-dispatch
# to a private worker whose signature is `where {IT<:IntegerHalf, T}`.  The worker therefore
# sees two indices of one concrete type and never a `Rational`, and a call mixing the two
# kinds of index is refused at the boundary with an explanation rather than a bare
# `MethodError`; the three `_rotors` functions pass their indices along to be normalized
# there.  Every quantity the workers form from the indices — the pixel count `Ysize(abs(s),
# ℓₘₐₓ)`, the number of rings ℓₘₐₓ - |s| + 1, the 2j+1 points on ring j, and the count of
# ulps `±ceil(abs(s))` — is an `Int` for either kind, so the workers need no branch on the
# kind and the integer path is exactly what it was.  A spin weight with |s| > ℓₘₐₓ describes
# no modes at all, and all of these functions refuse it with the same message before any
# point is placed.  The Driscoll–Healy and McEwen–Wiaux grids further down take integer indices
# only: they do not depend on `s` at all, and no transform defaults to them.

@doc raw"""
    golden_ratio_spiral_pixels(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels generated by the golden-ratio spiral.  Successive pixels
are separated by the azimuthal angle ``Δϕ = 2π(2-φ)``, and are uniformly distributed in
``\cos θ``.

This is a common angular pattern of phyllotaxis in plants, found in sunflowers, pine cones,
and artichokes, for example.  Wrapped around 𝕊², this is a very reasonable-looking
pixelization, with fairly uniform distance between neighbors, and approximate isotropy.  No
two pixels will share the same values of either ``θ`` or ``ϕ``.  Also note that no point is
present on either the North or South poles.

The number of pixels is [`Ysize(abs(s), ℓₘₐₓ)`](@ref Ysize), the number of modes of spin
weight `s` with ``|s| ≤ ℓ ≤ ℓₘₐₓ``, which is ``(ℓₘₐₓ+1)^2 - s^2`` for either kind of index.
The spin weight and `ℓₘₐₓ` may be integers or half-odd-integers, the latter passed as
`Rational`s with denominator 2, as in `golden_ratio_spiral_pixels(1//2, 7//2)`.  The two
must be of one kind; a call that mixes them, such as `golden_ratio_spiral_pixels(1//2, 3)`,
is an error, and so is a spin weight with ``|s| > ℓₘₐₓ``, for which there are no modes.

This is also known as the "Fibonacci sphere" or "Fibonacci lattice" — though Fibonacci had
nothing to do with it; later authors pointed out relationships between his sequence and the
golden ratio.

The returned quantity is a vector of 2-SVectors providing the spherical coordinates of each
pixel.  See also [`golden_ratio_spiral_rotors`](@ref) for the corresponding `Rotor`s.
"""
function golden_ratio_spiral_pixels(
    s::IndexArgument, ℓₘₐₓ::IndexArgument, ::Type{T}=Float64
) where T
    golden_ratio_spiral_pixels(unify_indices(s, ℓₘₐₓ)..., T)
end
function golden_ratio_spiral_pixels(
    s::IT, ℓₘₐₓ::IT, ::Type{T}
) where {IT<:IntegerHalf, T}
    if abs(s) > ℓₘₐₓ
        error("|s|=$(abs(s)) exceeds ℓₘₐₓ=$ℓₘₐₓ; there are no such modes.")
    end
    golden_ratio_spiral(Ysize(abs(s), ℓₘₐₓ), T)
end

# The spiral of any number `N` of points, which `leja_pixels` also uses, with more points
# than modes, as its set of candidates
function golden_ratio_spiral(N::Int, ::Type{T}) where {T}
    let π = T(π), φ = T(MathConstants.φ)
        # Note: the formula used here looks different from some sources,
        # but just represents spiraling in the opposite direction.
        Δϕ = 2π * (2 - φ)
        ϕ = (0:N-1) * Δϕ
        cosθ = LinRange{T}(1, -1, N+1)[begin:end-1] .- 1/T(N)
        [@SVector [acos(cosθ), ϕ] for (cosθ, ϕ) in zip(cosθ, ϕ)]
    end
end

@doc raw"""
    golden_ratio_spiral_rotors(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels generated by the golden-ratio spiral.

See [`golden_ratio_spiral_pixels`](@ref) for more detailed explanation, including the
half-odd-integer values that `s` and `ℓₘₐₓ` may take.  The quantity returned by this
function is a vector of `Rotor`s providing each pixel.
"""
function golden_ratio_spiral_rotors(
    s::IndexArgument, ℓₘₐₓ::IndexArgument, ::Type{T}=Float64
) where T
    from_spherical_coordinates.(golden_ratio_spiral_pixels(s, ℓₘₐₓ, T))
end

@doc raw"""
    leja_pixels(s, ℓₘₐₓ, [T=Float64]; oversampling=2)

Choose [`Ysize(abs(s), ℓₘₐₓ)`](@ref Ysize) pixels — as many as there are modes of spin
weight `s` with ``|s| ≤ ℓ ≤ ℓₘₐₓ`` — so that the matrix of spin-weighted spherical harmonics
at those points is well conditioned.  This is needed to solve for the mode weights from
function values at exactly that many points.

The golden-ratio spiral of [`golden_ratio_spiral_pixels`](@ref) spreads its points evenly,
but that is not what such a solve needs, and with exactly as many points as modes the matrix
becomes badly conditioned as ℓₘₐₓ grows: its condition number is about ``10^4`` at ℓₘₐₓ =
16, ``10^5`` at 32 and ``10^{14}`` at 64.  The points chosen here are "discrete Leja points"
[BosEtAl_2010](@cite), which approximate the Fekete points that maximize the determinant of
the matrix: the harmonics are evaluated on a golden-ratio spiral of `oversampling` times as
many candidate points, and an LU decomposition with partial pivoting of that tall matrix
picks, one row at a time, the candidate that is least well represented by those already
picked.  With the default `oversampling=2`, the condition number is about 30 at ℓₘₐₓ = 16,
70–100 at 32 and 200–400 at 64, for either ``s = 0`` or ``s = 2``, and a round trip through
[`SSHTMatrix`](@ref) on these points loses about 2 digits at ℓₘₐₓ = 64 rather than all of
them.  (Up to ℓₘₐₓ ≈ 12 the two are comparable, with condition numbers of order 10, and the
spiral is sometimes slightly the better; beyond that it degrades and these points do not.)
Larger values of `oversampling` did not help consistently in tests, and cost more.

The points depend on `s`, not just on their number, because the matrix does.  They are a
subset of that spiral, returned in its order (from the north pole to the south), and are
deterministic.  The cost is that of the LU decomposition of an ``N_c × N`` matrix, with
``N`` the number of modes and ``N_c`` the number of candidates — about 2–3 times that of the
decomposition [`SSHTMatrix`](@ref) itself performs, or 2–3 seconds at ℓₘₐₓ = 64 — and its
``O(N^2)`` storage.  These are the default sample points of [`SSHTMatrix`](@ref).

The spin weight and `ℓₘₐₓ` may be integers or half-odd-integers, as for
[`golden_ratio_spiral_pixels`](@ref), on the same terms.  The returned quantity is a vector
of 2-SVectors providing the spherical coordinates of each pixel.  See also
[`leja_rotors`](@ref) for the corresponding `Rotor`s.
"""
function leja_pixels(
    s::IndexArgument, ℓₘₐₓ::IndexArgument, ::Type{T}=Float64; oversampling::Real=2
) where T
    leja_pixels(unify_indices(s, ℓₘₐₓ)..., T, oversampling)
end
function leja_pixels(
    s::IT, ℓₘₐₓ::IT, ::Type{T}, oversampling::Real
) where {IT<:IntegerHalf, T}
    if abs(s) > ℓₘₐₓ
        error("|s|=$(abs(s)) exceeds ℓₘₐₓ=$ℓₘₐₓ; there are no such modes.")
    end
    if !(oversampling ≥ 1)
        throw(ArgumentError(
            "oversampling=$oversampling must be at least 1, so that there are at least as many "
            * "candidates as points to choose."
        ))
    end
    N = Ysize(abs(s), ℓₘₐₓ)
    candidates = golden_ratio_spiral(ceil(Int, oversampling * N), T)
    # The rows of Y are the candidates; the first N row pivots are the points chosen.  With
    # `check=false` a numerically singular trailing block is not an error: the pivots are
    # chosen before it is reached.
    Y = sYlm_matrix(from_spherical_coordinates.(candidates), ℓₘₐₓ, s)
    F = LinearAlgebra.lu!(Y, LinearAlgebra.RowMaximum(); check=false)
    candidates[sort(F.p[1:N])]
end

@doc raw"""
    leja_rotors(s, ℓₘₐₓ, [T=Float64]; oversampling=2)

Choose pixels on which the spin-weighted spherical harmonics are well conditioned, as
discrete Leja points drawn from a golden-ratio spiral.

See [`leja_pixels`](@ref) for more detailed explanation, including the half-odd-integer
values that `s` and `ℓₘₐₓ` may take.  The quantity returned by this function is a vector of
`Rotor`s providing each pixel.
"""
function leja_rotors(
    s::IndexArgument, ℓₘₐₓ::IndexArgument, ::Type{T}=Float64; oversampling::Real=2
) where T
    from_spherical_coordinates.(leja_pixels(s, ℓₘₐₓ, T; oversampling))
end

@doc raw"""
    sorted_rings(s, ℓₘₐₓ, [T=Float64])

Compute locations of a series of rings labelled by ``j ∈ |s|:ℓₘₐₓ`` (analogous to ``ℓ``).
Each ring will contain ``k = 2j+1`` (analogous to ``m``) pixels distributed evenly around the
ring.  These rings are then sorted, so that the ring with the most pixels
(``j = ℓₘₐₓ``) is closest to the equator, and the next-largest ring is placed just above or
below the equator (depending on the sign of ``s``), the next just below or above, and so on.
This is generally a fairly good first guess when minimizing the condition number of matrices
used to solve for mode weights from function values, and for ``s = 0`` it gives the default
rings of the Minimal algorithm.  For ``s ≠ 0`` these rings are badly conditioned, and the
Minimal algorithm uses the different arrangement of [`minimal_rings`](@ref) instead; see
[`SSHTMinimal`](@ref).

The spin weight and `ℓₘₐₓ` may be integers or half-odd-integers, the latter passed as
`Rational`s with denominator 2, as in `sorted_rings(1//2, 7//2)`; the two must be of one
kind.  There are then ``ℓₘₐₓ - |s| + 1`` rings, and ring ``j`` has ``2j+1`` pixels, both of
which are whole numbers for either kind of index.  A spin weight with ``|s| > ℓₘₐₓ``
describes no modes, and is an error.

This function does not provide the individual pixels; it just provides the colatitude values
of the rings on which the pixels will be placed.  The pixels themselves are provided by
[`sorted_ring_pixels`](@ref).
"""
function sorted_rings(
    s::IndexArgument, ℓₘₐₓ::IndexArgument, ::Type{T}=Float64
) where T
    sorted_rings(unify_indices(s, ℓₘₐₓ)..., T)
end
function sorted_rings(s::IT, ℓₘₐₓ::IT, ::Type{T}) where {IT<:IntegerHalf, T}
    if abs(s) > ℓₘₐₓ
        error("|s|=$(abs(s)) exceeds ℓₘₐₓ=$ℓₘₐₓ; there are no such modes.")
    end
    # The spin weight is used here as a count of ulps by which the comparison point is moved
    # off the equator, which is what breaks the ties in the sort below and places the second
    # ring above or below the equator according to the sign of `s`.  A count must be a whole
    # number, so a half-odd spin weight is rounded away from zero, which keeps its sign and
    # so makes the order for -s the mirror image of that for s: for an `Integer` this is the
    # identity, and for a `HalfOddInteger` it is the `Int` just beyond.  (Rounding up instead
    # would send s = -1/2 to 0, which gives the order of s = 0.)
    let πo2 = prevfloat(T(π)/2, s < 0 ? -ceil(abs(s)) : ceil(abs(s)))
        sort(
            collect(LinRange{T}(0, π, 2+ℓₘₐₓ-abs(s)+1))[begin+1:end-1],
            lt=(x,y)->(abs(x-πo2)<abs(y-πo2)),
            rev=true
        )
    end
end


"""
    sorted_ring_pixels(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with `Ysize(abs(s), ℓₘₐₓ)` pixels, distributed in the rings provided by
[`sorted_rings`](@ref).  That count is the number of modes of spin weight `s` with ``|s| ≤ ℓ
≤ ℓₘₐₓ``, which is ``(ℓₘₐₓ+1)²-s²``; see the documentation of [`sorted_rings`](@ref) for
more description, including the half-odd-integer values that `s` and `ℓₘₐₓ` may take.

The returned quantity is a vector of 2-SVectors containing the spherical coordinates of each
pixel.  See also [`sorted_ring_rotors`](@ref) for the corresponding `Rotor`s.
"""
function sorted_ring_pixels(
    s::IndexArgument, ℓₘₐₓ::IndexArgument, ::Type{T}=Float64
) where T
    sorted_ring_pixels(unify_indices(s, ℓₘₐₓ)..., T)
end
function sorted_ring_pixels(s::IT, ℓₘₐₓ::IT, ::Type{T}) where {IT<:IntegerHalf, T}
    θrings = sorted_rings(s, ℓₘₐₓ, T)
    [
        @SVector [θ, ϕ]
        for (j,θ) ∈ zip(abs(s):ℓₘₐₓ, θrings)
        for ϕ ∈ LinRange{T}(0, 2T(π), 2j+2)[begin:end-1]
    ]
end

"""
    sorted_ring_rotors(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with `Ysize(abs(s), ℓₘₐₓ)` pixels, distributed in the rings provided by
[`sorted_rings`](@ref).  That count is the number of modes of spin weight `s` with ``|s| ≤ ℓ
≤ ℓₘₐₓ``, which is ``(ℓₘₐₓ+1)²-s²``; see the documentation of [`sorted_rings`](@ref) for
more description, including the half-odd-integer values that `s` and `ℓₘₐₓ` may take.

The returned quantity is a vector of `Rotor`s.  See also [`sorted_ring_pixels`](@ref) for
the corresponding spherical coordinates.
"""
function sorted_ring_rotors(
    s::IndexArgument, ℓₘₐₓ::IndexArgument, ::Type{T}=Float64
) where T
    from_spherical_coordinates.(sorted_ring_pixels(s, ℓₘₐₓ, T))
end

"""
    fejer1_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by Fejér's first
rule, using weights provided by [`fejer1`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
"""
function fejer1_rings(N, ::Type{T}=Float64) where T
    # Eq. (12) of Reinecke and Seljebotn
    let π = T(π)
        [(2n+1)*π/2N for n ∈ 0:N-1]
    end
end

"""
    fejer2_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by Fejér's second
rule, using weights provided by [`fejer2`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
"""
function fejer2_rings(N, ::Type{T}=Float64) where T
    # Eq. (13) of Reinecke and Seljebotn, with N adjusted to reflect actual number of elements
    let π = T(π)
        [n*π/(N+1) for n ∈ 1:N]
    end
end

"""
    clenshaw_curtis_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by the
Clenshaw-Curtis rule, using weights provided by [`clenshaw_curtis`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
"""
function clenshaw_curtis_rings(N, ::Type{T}=Float64) where T
    # Eq. (14) of Reinecke and Seljebotn, with N adjusted to reflect actual number of elements
    let π = T(π)
        [n*π/(N-1) for n ∈ 0:N-1]
    end
end

@doc raw"""
    driscoll_healy_pixels([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [DriscollHealy_1994](@citet) equiangular grid:

> Let ``f(θ, ϕ)`` be a band-limited function such that ``\hat{f}(l, m) = 0`` for ``l
> ≥ b``.  We sample the function at the equiangular grid of points ``(θ_i, ϕ_j)``,
> ``i = 0, \ldots, 2b-1``, ``j = 0, \ldots, 2b-1``, where ``θ_i = π i/2b`` and
> ``ϕ_j = π j/b``.

The returned quantity is a vector of 2-SVectors providing the spherical coordinates of each
pixel.  See also [`driscoll_healy_rotors`](@ref) for the corresponding `Rotor`s.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
function driscoll_healy_pixels(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    let π = T(π)
        b = ℓₘₐₓ + 1
        [
            @SVector [π*i/2b, π*j/b]
            for i ∈ 0:(2b-1)
            for j ∈ 0:(2b-1)
        ]
    end
end
driscoll_healy_pixels(ℓₘₐₓ, ::Type{T}=Float64) where T = driscoll_healy_pixels(0, ℓₘₐₓ, T)

@doc raw"""
    driscoll_healy_rotors(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [DriscollHealy_1994](@citet) equiangular grid.

See [`driscoll_healy_pixels`](@ref) for more detailed explanation.  The quantity returned by
this function is a vector of `Rotor`s providing each pixel.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
function driscoll_healy_rotors(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    from_spherical_coordinates.(driscoll_healy_pixels(s, ℓₘₐₓ, T))
end
driscoll_healy_rotors(ℓₘₐₓ, ::Type{T}=Float64) where T = driscoll_healy_rotors(0, ℓₘₐₓ, T)


@doc raw"""
    mcewen_wiaux_pixels([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [McEwenWiaux_2011](@citet) equiangular grid.
They consider "signals on the sphere bandlimited at ``L``, that is signals such that ``{}_sf_{ℓm}
= 0, ∀ℓ ≥ L``", so that ``L = ℓₘₐₓ + 1`` here, and write:

> We adopt an equiangular sampling of the sphere with sample positions given by ``θ_t =
> \frac{π(2t+1)}{2L-1}``, where ``t ∈ \{0, 1, …, L-1\}`` […] and ``ϕ_p = \frac{2πp}{2L-1}``,
> where ``p ∈ \{0, 1, …, 2L-2\}``.

These are the ``L(2L-1)`` points returned, ordered with ``ϕ`` varying fastest.  The last ring,
``t = L-1``, lies at the south pole ``θ = π``, and all ``2L-1`` of its points are included, as
distinct rotors that differ by a rotation about the pole; McEwen and Wiaux count the pole once,
for ``(L-1)(2L-1)+1`` samples.  Their algorithm also extends the ``θ`` domain to ``[0, 2π)``,
reflecting the samples through the south pole to ``t ∈ \{L, …, 2L-2\}``, but those are not
further sample positions on the sphere, and are not returned.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
function mcewen_wiaux_pixels(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    let π = T(π), L = ℓₘₐₓ + 1
        # The ratio is formed first, so that it is exactly 1 on the last ring, which is then
        # exactly at the south pole rather than an ulp to either side of it.
        [
            @SVector [π * (T(2t+1) / T(2L - 1)), 2π*p / (2L - 1)]
            for t ∈ 0:(L - 1)
            for p ∈ 0:(2L - 2)
        ]
    end
end
mcewen_wiaux_pixels(ℓₘₐₓ, ::Type{T}=Float64) where T = mcewen_wiaux_pixels(0, ℓₘₐₓ, T)

@doc raw"""
    mcewen_wiaux_rotors([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [McEwenWiaux_2011](@citet) equiangular grid.

See [`mcewen_wiaux_pixels`](@ref) for more detailed explanation.  The quantity returned by
this function is a vector of `Rotor`s providing each pixel.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
function mcewen_wiaux_rotors(s, ℓₘₐₓ, ::Type{T}=Float64) where T
    from_spherical_coordinates.(mcewen_wiaux_pixels(s, ℓₘₐₓ, T))
end
mcewen_wiaux_rotors(ℓₘₐₓ, ::Type{T}=Float64) where T = mcewen_wiaux_rotors(0, ℓₘₐₓ, T)
