# Pixelizations of the sphere.
#
# The golden-ratio spiral, the Leja points and the sorted rings are sized by the spin weight
# `s` and the band limit `ℓₘₐₓ`, which may be integers or half-odd-integers, the latter
# passed as `Rational`s with denominator 2 or as `HalfOddInteger`s.  Each of these functions
# is defined with `@index_methods`, so that its body sees two indices of one kind, `Int` or
# `HalfOddInteger`, and a call that mixes the kinds, or passes an index of another integer
# type, is refused with an explanation.  Every quantity the bodies form from the indices —
# the pixel count `Ysize(abs(s), ℓₘₐₓ)`, the number of rings ℓₘₐₓ - |s| + 1, and the 2j+1
# points on ring j — is an `Int` for either kind, so the bodies need no branch on the kind.
# A spin weight with |s| > ℓₘₐₓ describes no modes at all, and all of these functions refuse
# it with the same message before any point is placed.
#
# The point sets do not depend on the element type `T` in which they are returned, beyond
# the rounding of each coordinate: the golden-ratio spiral's colatitudes and azimuths are
# formed from exact integers, the Leja points are chosen in `Float64` whatever `T` is, and
# the rings are ordered by exact integer keys.  The Driscoll–Healy and McEwen–Wiaux grids
# further down are defined for integer indices only, and no transform defaults to them.

# Refuse a spin outside the band limit of ℓₘₐₓ; for integer indices this includes every
# negative ℓₘₐₓ.
function check_band_limit(s, ℓₘₐₓ)
    if abs(s) > ℓₘₐₓ
        throw(ArgumentError("|s|=$(abs(s)) exceeds ℓₘₐₓ=$ℓₘₐₓ; there are no such modes."))
    end
    nothing
end

@doc raw"""
    golden_ratio_spiral_pixels(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels generated by the golden-ratio spiral.  Successive pixels
are separated by the azimuthal angle ``Δϕ = 2π(2-φ)``, and are uniformly distributed in
``\cos θ``.

This is a common angular pattern of [phyllotaxis](https://en.wikipedia.org/wiki/Phyllotaxis)
in plants, found in sunflowers, pine cones, and artichokes, for example.  Wrapped around
𝕊², this is a very reasonable-looking pixelization, with fairly uniform distance between
neighbors, and approximate isotropy.  No two pixels will share the same values of either
``θ`` or ``ϕ``.  Also note that no point is present on either the North or South poles.

The number of pixels is [`Ysize(abs(s), ℓₘₐₓ)`](@ref Ysize), the number of modes of spin
weight `s` with ``|s| ≤ ℓ ≤ ℓₘₐₓ``, which is ``(ℓₘₐₓ+1)^2 - s^2`` for either kind of index.
The spin weight and `ℓₘₐₓ` may be integers or half-odd-integers, the latter passed as
`Rational`s with denominator 2, as in `golden_ratio_spiral_pixels(1//2, 7//2)`.  The two
must be of one kind; a call that mixes them, such as `golden_ratio_spiral_pixels(1//2, 3)`,
is an error, and so is a spin weight with ``|s| > ℓₘₐₓ``, for which there are no modes.

Pixel ``k = 0, 1, …, N-1`` of the ``N`` pixels has ``\cos θ = 1 - (2k+1)/N``, the center of
the ``k``th of ``N`` bands of equal width in ``\cos θ``, and so of equal area.  Its azimuth
is ``kΔϕ`` reduced modulo ``2π``, so that every ``ϕ`` lies in ``[0, 2π)``.  Both coordinates
are formed from exact integer quantities — the reduction modulo ``2π`` is made in exact
arithmetic — so that their only errors are those of the final few roundings, of about an ulp
of `T`, and the pixels in different types `T` are roundings of the same points.

This is also known as the "Fibonacci sphere" or "Fibonacci lattice" — though Fibonacci had
nothing to do with it; later authors pointed out relationships between his sequence and the
golden ratio.

The returned quantity is a vector of 2-SVectors providing the spherical coordinates of each
pixel.  See also [`golden_ratio_spiral_rotors`](@ref) for the corresponding `Rotor`s.

Note that these points can be constructed analytically, as is done here, but do not lead to
very well conditioned matrices of spin-weighted spherical harmonics.  A somewhat better
choice is given by [`leja_pixels`](@ref), which chooses a subset of the points of a denser
golden-ratio spiral with better conditioning, and is the default for [`SSHTMatrix`](@ref).
"""
@index_methods function golden_ratio_spiral_pixels(
    s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64
) where {T}
    check_band_limit(s, ℓₘₐₓ)
    golden_ratio_spiral(Ysize(abs(s), ℓₘₐₓ), T)
end

# The spiral of any number `N` of points, which `leja_pixels` also uses, with more points
# than modes, as its set of candidates; or only the points of the spiral whose (1-based)
# positions are `indices`.
function golden_ratio_spiral(N::Int, ::Type{T}, indices=1:N) where {T}
    # Note: the formula used here looks different from some sources,
    # but just represents spiraling in the opposite direction.
    ϕ = golden_ratio_spiral_azimuths(indices .- 1, T)
    [@SVector [golden_ratio_spiral_colatitude(k, N, T), ϕₖ] for (k, ϕₖ) ∈ zip(indices, ϕ)]
end

# The colatitude of the point k = 1, …, N of the spiral.  The points are spaced uniformly in
# z = cos θ, at the centers z = 1 - (2k-1)/N of N bands of equal width 2/N, which by
# Archimedes' hat-box theorem are also bands of equal area.  Taking θ = acos(z) would be
# ill-conditioned near the poles, where the first and last points lie: dθ/dz = -1/sin θ, so
# the rounding error of z, about ε, becomes a relative error of about Nε/2 in the θ of the
# first point.  But both 1 - z = (2k-1)/N and 1 + z = (2N-2k+1)/N are exact ratios of
# integers, so N cos θ = N - 2k + 1 and N sin θ = N√((1-z)(1+z)) = √((2k-1)(2N-2k+1)) can be
# formed from integers, and the common factor N drops out of the two-argument arctangent,
# which is well conditioned for every θ in [0, π].  The only roundings are then those of the
# square root and the arctangent.  They are made in `Float64` for the smaller types, whose
# range could not hold the integers, and then rounded once to `T`.
function golden_ratio_spiral_colatitude(k::Int, N::Int, ::Type{T}) where {T}
    W = promote_type(T, Float64)
    T(atan(sqrt(W((2k-1)*(2N-2k+1))), W(N-2k+1)))
end

# The azimuths of the points k = 0, 1, … of the spiral, 2π times the fractional part of
# k(2-φ).  Formed as k times Δϕ = 2π(2-φ) in `T`, each would inherit the rounding error of
# Δϕ multiplied by k, which for the thousands of points of a spiral at moderate ℓₘₐₓ costs
# several digits of the azimuth in `Float32`, and makes the spirals of different types
# differ by more than their roundings.  So the fractional part is computed exactly, as k
# times a fixed-point approximation of 2-φ whose error, multiplied by k, stays far below the
# precision of `T`: with 128 bits for the types of at most 53 bits, whose azimuth is then
# formed as a double-length product in `Float64` and rounded once to `T`; and with 64 bits
# more than the precision of `T` for any other type, in `BigInt` arithmetic.
#
# 2 - φ = (3 - √5)/2, so its fixed-point approximation with P bits, the integer nearest to
# (2 - φ) 2ᴾ, follows from the integer square root of 5⋅4ᴾ.
golden_ratio_fraction(P) = (3 * big(2)^P - isqrt(5 * big(4)^P)) >> 1
const golden_ratio_fraction_128 = UInt128(golden_ratio_fraction(128))
const two_pi_hi = Float64(2big(π))
const two_pi_lo = Float64(2big(π) - two_pi_hi)

function golden_ratio_spiral_azimuths(
    ks, ::Type{T}
) where {T<:Union{Float16, Float32, Float64}}
    map(ks) do k
        # The fraction F/2¹²⁸ of a turn, split into its leading 53 bits, exactly, and the
        # rest, rounded; then 2π times that, with the error of the leading product recovered
        # by `fma`.  The product of `UInt128`s wraps around, which is reduction modulo 1.
        F = UInt128(k) * golden_ratio_fraction_128
        # `Float64` has 53 bits of precision.  We shift `F` by (128-53) = 75 bits to get the
        # leading 53 bits of `F` as a `Float64`, and multiply by 2⁻⁵³ to get the fraction of
        # a turn to `Float64` precision.
        hi = Float64(F >> 75) * 0x1p-53
        # Now we mask off the bits we just got, and multiply by 2⁻¹²⁸ to get the remaining
        # fraction of a turn, to the remaining precision available in the 128 bits of the
        # `UInt128`.
        lo = Float64(F & ((UInt128(1) << 75) - 1)) * 0x1p-128
        # The rest of this just preserves an ulp or two, but is fast and tested.
        p = two_pi_hi * hi
        e = fma(two_pi_hi, hi, -p)
        T(p + (e + fma(two_pi_hi, lo, two_pi_lo * hi)))
    end
end
function golden_ratio_spiral_azimuths(ks, ::Type{T}) where {T}
    P = 64 + (applicable(precision, T) ? precision(T) : precision(BigFloat))
    C = golden_ratio_fraction(P)
    one_turn = big(2)^P
    twoπ = 2T(π)
    map(k -> twoπ * T(BigFloat(mod(k * C, one_turn)) / BigFloat(one_turn)), ks)
end

@doc raw"""
    golden_ratio_spiral_rotors(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels generated by the golden-ratio spiral.

See [`golden_ratio_spiral_pixels`](@ref) for more detailed explanation, including the
half-odd-integer values that `s` and `ℓₘₐₓ` may take.  The quantity returned by this
function is a vector of `Rotor`s providing each pixel.
"""
@index_methods golden_ratio_spiral_rotors(
    s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64
) where {T} = from_spherical_coordinates.(golden_ratio_spiral_pixels(s, ℓₘₐₓ, T))

@doc raw"""
    leja_pixels(s, ℓₘₐₓ, [T=Float64]; oversampling=2)

Choose [`Ysize(abs(s), ℓₘₐₓ)`](@ref Ysize) pixels — as many as there are modes of spin
weight `s` with ``|s| ≤ ℓ ≤ ℓₘₐₓ`` — so that the matrix of spin-weighted spherical harmonics
at those points is well conditioned.  This is needed to solve for the mode weights from
function values at exactly that many points.

The golden-ratio spiral of [`golden_ratio_spiral_pixels`](@ref) spreads its points evenly,
but that is not what such a solve needs, and with exactly as many points as modes the matrix
becomes badly conditioned as ℓₘₐₓ grows: its condition number is about ``10^4`` at ℓₘₐₓ =
16, ``10^5`` at 32 and ``10^{14}`` at 64.  The points chosen here are "discrete Leja points"
[BosEtAl_2010](@cite), which approximate the Fekete points that maximize the determinant of
the matrix: the harmonics are evaluated on a golden-ratio spiral of `oversampling` times as
many candidate points, and an LU decomposition with partial pivoting of that tall matrix
picks, one row at a time, the candidate that is least well represented by those already
picked.  With the default `oversampling=2`, the condition number is about 30 at ℓₘₐₓ = 16,
70–100 at 32 and 200–400 at 64, for either ``s = 0`` or ``s = 2``, and a round trip through
[`SSHTMatrix`](@ref) on these points loses about 3 digits at ℓₘₐₓ = 64 rather than all of
them.  (Up to ℓₘₐₓ ≈ 12 the two are comparable, with condition numbers of order 10, and the
spiral is sometimes slightly the better; beyond that it degrades and these points do not.)
Larger values of `oversampling`, which must be finite and at least 1, did not help
consistently in tests, and cost more.

The points depend on `s`, not just on their number, because the matrix does.  They are a
subset of that spiral, returned in its order (from the north pole to the south), and are
deterministic.  The candidates are chosen in `Float64`, by LAPACK's LU decomposition of the
harmonics at the `Float64` spiral, whatever `T` is, and only the chosen candidates are then
evaluated in `T`; so every `T` gets the same points, each rounded to `T`, and a function
sampled in one precision can be analysed in another.  The cost is that of the LU
decomposition of an ``N_c × N`` matrix, with ``N`` the number of modes and ``N_c`` the number
of candidates — about 2–3 times that of the decomposition [`SSHTMatrix`](@ref) itself
performs in `Float64`, or 2–3 seconds at ℓₘₐₓ = 64 — and its ``O(N^2)`` storage.  These are
the default sample points of [`SSHTMatrix`](@ref).

The spin weight and `ℓₘₐₓ` may be integers or half-odd-integers, as for
[`golden_ratio_spiral_pixels`](@ref), on the same terms.  The returned quantity is a vector
of 2-SVectors providing the spherical coordinates of each pixel.  See also
[`leja_rotors`](@ref) for the corresponding `Rotor`s.
"""
@index_methods function leja_pixels(
    s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64; oversampling::Real=2
) where {T}
    check_band_limit(s, ℓₘₐₓ)
    if !(isfinite(oversampling) && oversampling ≥ 1)
        throw(ArgumentError(
            "oversampling=$oversampling must be at least 1, and finite, so that there are at "
            * "least as many candidates as points to choose."
        ))
    end
    N = Ysize(abs(s), ℓₘₐₓ)
    Nc = ceil(Int, oversampling * N)
    candidates = golden_ratio_spiral(Nc, Float64)
    # The rows of Y are the candidates; the first N row pivots are the points chosen.  With
    # `check=false` a numerically singular trailing block is not an error: the pivots are
    # chosen before it is reached.
    Y = sYlm_matrix(from_spherical_coordinates.(candidates), ℓₘₐₓ, s)
    F = LinearAlgebra.lu!(Y, LinearAlgebra.RowMaximum(); check=false)
    chosen = sort(F.p[1:N])
    T === Float64 ? candidates[chosen] : golden_ratio_spiral(Nc, T, chosen)
end

@doc raw"""
    leja_rotors(s, ℓₘₐₓ, [T=Float64]; oversampling=2)

Choose pixels on which the spin-weighted spherical harmonics are well conditioned, as
discrete Leja points drawn from a golden-ratio spiral.

See [`leja_pixels`](@ref) for more detailed explanation, including the half-odd-integer
values that `s` and `ℓₘₐₓ` may take.  The quantity returned by this function is a vector of
`Rotor`s providing each pixel.
"""
@index_methods function leja_rotors(
    s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64; oversampling::Real=2
) where {T}
    from_spherical_coordinates.(leja_pixels(s, ℓₘₐₓ, T; oversampling))
end

@doc raw"""
    sorted_rings(s, ℓₘₐₓ, [T=Float64])

Compute locations of a series of rings labelled by ``j ∈ |s|:ℓₘₐₓ`` (analogous to ``ℓ``).
Each ring will contain ``k = 2j+1`` (analogous to ``m``) pixels distributed evenly around
the ring.  These rings are then sorted, so that the ring with the most pixels (``j = ℓₘₐₓ``)
is closest to the equator, and the next-largest ring is placed just above or below the
equator (depending on the sign of ``s``), the next just below or above, and so on.  This is
generally a fairly good first guess when minimizing the condition number of matrices used to
solve for mode weights from function values, and for ``s = 0`` it gives the default rings of
the Minimal algorithm.  For ``s ≠ 0`` these rings are badly conditioned, and the Minimal
algorithm uses the different arrangement of [`minimal_rings`](@ref) instead; see
[`SSHTMinimal`](@ref).

The rings occupy the ``n = ℓₘₐₓ - |s| + 1`` interior points of an equally spaced grid on
``[0, π]``, and are assigned to them in order of size, from the slots farthest from the
equator to the nearest.  Two slots that are mirror images of each other across the equator
are equally far from it, and of the two rings assigned to such a pair, the larger goes to
the northern slot for ``s ≥ 0`` and to the southern for ``s < 0``.  The order is decided by
the positions of the slots in the grid, not by their rounded colatitudes, so it is the same
for every `T`, and for ``s ≠ 0`` the rings for ``-s`` are exactly the mirror images of those
for ``s``.  (For ``s = 0`` the larger ring of each mirror pair is the northern one, so the
rings are not symmetric about the equator.)

The spin weight and `ℓₘₐₓ` may be integers or half-odd-integers, the latter passed as
`Rational`s with denominator 2, as in `sorted_rings(1//2, 7//2)`; the two must be of one
kind.  There are then ``ℓₘₐₓ - |s| + 1`` rings, and ring ``j`` has ``2j+1`` pixels, both of
which are whole numbers for either kind of index.  A spin weight with ``|s| > ℓₘₐₓ``
describes no modes, and is an error.

This function does not provide the individual pixels; it just provides the colatitude values
of the rings on which the pixels will be placed.  The pixels themselves are provided by
[`sorted_ring_pixels`](@ref).
"""
@index_methods function sorted_rings(s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T}
    check_band_limit(s, ℓₘₐₓ)
    n = ℓₘₐₓ - abs(s) + 1
    slots = collect(LinRange{T}(0, π, n + 2))[begin+1:end-1]
    slots[equatorward_order(n, s)]
end

# The order in which rings of increasing size fill `n` equally spaced slots, numbered from
# the north pole: from the slots farthest from the equator to the nearest.  The distance of
# slot i from the equator, in half slot spacings, is the integer |2i - (n+1)|, so the order
# is exact.  Mirror-image slots i and n+1-i are equally far from the equator, and the second
# ring of the two assigned to them, which is the larger, goes to the northern one for s ≥ 0
# and to the southern one for s < 0, so that the order for -s is the mirror image of that
# for s.
function equatorward_order(n::Int, s)
    north_last = s ≥ 0
    sort(1:n; by=i -> (-abs(2i - (n + 1)), north_last ? -i : i))
end


"""
    sorted_ring_pixels(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with `Ysize(abs(s), ℓₘₐₓ)` pixels, distributed in the rings provided by
[`sorted_rings`](@ref).  That count is the number of modes of spin weight `s` with ``|s| ≤ ℓ
≤ ℓₘₐₓ``, which is ``(ℓₘₐₓ+1)²-s²``; see the documentation of [`sorted_rings`](@ref) for
more description, including the half-odd-integer values that `s` and `ℓₘₐₓ` may take.

The returned quantity is a vector of 2-SVectors containing the spherical coordinates of each
pixel.  See also [`sorted_ring_rotors`](@ref) for the corresponding `Rotor`s.
"""
@index_methods function sorted_ring_pixels(
    s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64
) where {T}
    θrings = sorted_rings(s, ℓₘₐₓ, T)
    [
        @SVector [θ, ϕ]
        for (j,θ) ∈ zip(abs(s):ℓₘₐₓ, θrings)
        for ϕ ∈ LinRange{T}(0, 2T(π), 2j+2)[begin:end-1]
    ]
end

"""
    sorted_ring_rotors(s, ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with `Ysize(abs(s), ℓₘₐₓ)` pixels, distributed in the rings provided by
[`sorted_rings`](@ref).  That count is the number of modes of spin weight `s` with ``|s| ≤ ℓ
≤ ℓₘₐₓ``, which is ``(ℓₘₐₓ+1)²-s²``; see the documentation of [`sorted_rings`](@ref) for
more description, including the half-odd-integer values that `s` and `ℓₘₐₓ` may take.

The returned quantity is a vector of `Rotor`s.  See also [`sorted_ring_pixels`](@ref) for
the corresponding spherical coordinates.
"""
@index_methods sorted_ring_rotors(
    s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64
) where {T} = from_spherical_coordinates.(sorted_ring_pixels(s, ℓₘₐₓ, T))

"""
    fejer1_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by Fejér's first
rule, using weights provided by [`fejer1`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
The number of rings `N` must be at least 1.
"""
function fejer1_rings(N, ::Type{T}=Float64) where T
    if N < 1
        throw(ArgumentError("`fejer1_rings` needs at least one ring; got N=$N."))
    end
    # Eq. (12) of Reinecke and Seljebotn
    let π = T(π)
        [(2n+1)*π/2N for n ∈ 0:N-1]
    end
end

"""
    fejer2_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by Fejér's second
rule, using weights provided by [`fejer2`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
The number of rings `N` must be at least 1.
"""
function fejer2_rings(N, ::Type{T}=Float64) where T
    if N < 1
        throw(ArgumentError("`fejer2_rings` needs at least one ring; got N=$N."))
    end
    # Eq. (13) of Reinecke and Seljebotn, with N adjusted to reflect actual number of elements
    let π = T(π)
        [n*π/(N+1) for n ∈ 1:N]
    end
end

"""
    clenshaw_curtis_rings(N, [T=Float64])

Values of the colatitude coordinate (``θ``) appropriate for quadrature by the
Clenshaw-Curtis rule, using weights provided by [`clenshaw_curtis`](@ref).

Note that the first argument to this function is `N`, rather than the `ℓₘₐₓ` used in some
other functions.  For spin-weighted spherical harmonics, you may want to use `N=2ℓₘₐₓ+1`.
The number of rings `N` must be at least 2, since the rings include both poles.
"""
function clenshaw_curtis_rings(N, ::Type{T}=Float64) where T
    if N < 2
        throw(ArgumentError(
            "`clenshaw_curtis_rings` needs at least two rings, one at each pole; got N=$N."
        ))
    end
    # Eq. (14) of Reinecke and Seljebotn, with N adjusted to reflect actual number of elements
    let π = T(π)
        [n*π/(N-1) for n ∈ 0:N-1]
    end
end

# The two equiangular grids below are defined for integer indices only, which
# `@index_methods integer_only` enforces for the spin weight as well as the band limit,
# although neither grid uses the spin weight.  A half-integer call is told which
# pixelizations to use instead.  What is left to check is the sign of the band limit.
function check_equiangular_band_limit(grid, ℓₘₐₓ)
    if ℓₘₐₓ < 0
        throw(ArgumentError("The $grid grid needs a non-negative band limit; got ℓₘₐₓ=$ℓₘₐₓ."))
    end
    nothing
end

@doc raw"""
    driscoll_healy_pixels([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [DriscollHealy_1994](@citet) equiangular grid.
They write:

> Let ``f(θ, ϕ)`` be a band-limited function such that ``\hat{f}(l, m) = 0`` for ``l ≥ b``.
> We sample the function at the equiangular grid of points ``(θ_i, ϕ_j)``, ``i = 0, \ldots,
> 2b-1``, ``j = 0, \ldots, 2b-1``, where ``θ_i = π i/2b`` and ``ϕ_j = π j/b``.

The band limit here is ``b = ℓₘₐₓ + 1``, and `ℓₘₐₓ` must be a non-negative integer.  The
grid is defined for integer indices only; functions of half-integer spin are sampled with
[`golden_ratio_spiral_pixels`](@ref), [`leja_pixels`](@ref) or [`sorted_ring_pixels`](@ref)
instead.

These are the ``(2b)^2`` points returned, ordered with ``ϕ`` varying fastest.  The first
ring, ``i = 0``, lies at the north pole ``θ = 0``, and all ``2b`` of its points are
included, as distinct rotors that differ by a rotation about the pole.  The grid does not
reach the south pole, since the largest colatitude is ``π(2b-1)/2b``.

The returned quantity is a vector of 2-SVectors providing the spherical coordinates of each
pixel.  See also [`driscoll_healy_rotors`](@ref) for the corresponding `Rotor`s.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.  It must be an integer, like `ℓₘₐₓ`.
"""
@index_methods integer_only (
    "Functions of half-integer spin may be sampled with `golden_ratio_spiral_pixels`, "
    * "`leja_pixels` or `sorted_ring_pixels`."
) function driscoll_healy_pixels(s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T}
    check_equiangular_band_limit("Driscoll–Healy", ℓₘₐₓ)
    let π = T(π)
        b = ℓₘₐₓ + 1
        [
            @SVector [π*i/2b, π*j/b]
            for i ∈ 0:(2b-1)
            for j ∈ 0:(2b-1)
        ]
    end
end
@index_methods integer_only (
    "Functions of half-integer spin may be sampled with `golden_ratio_spiral_pixels`, "
    * "`leja_pixels` or `sorted_ring_pixels`."
) driscoll_healy_pixels(ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T} =
    driscoll_healy_pixels(0, ℓₘₐₓ, T)

@doc raw"""
    driscoll_healy_rotors([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [DriscollHealy_1994](@citet) equiangular grid.

See [`driscoll_healy_pixels`](@ref) for more detailed explanation.  The quantity returned by
this function is a vector of `Rotor`s providing each pixel.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
@index_methods integer_only (
    "Functions of half-integer spin may be sampled with `golden_ratio_spiral_rotors`, "
    * "`leja_rotors` or `sorted_ring_rotors`."
) function driscoll_healy_rotors(s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T}
    from_spherical_coordinates.(driscoll_healy_pixels(s, ℓₘₐₓ, T))
end
@index_methods integer_only (
    "Functions of half-integer spin may be sampled with `golden_ratio_spiral_rotors`, "
    * "`leja_rotors` or `sorted_ring_rotors`."
) driscoll_healy_rotors(ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T} =
    driscoll_healy_rotors(0, ℓₘₐₓ, T)


@doc raw"""
    mcewen_wiaux_pixels([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [McEwenWiaux_2011](@citet) equiangular grid.
They consider "signals on the sphere bandlimited at ``L``, that is signals such that
``{}_sf_{ℓm} = 0, ∀ℓ ≥ L``", so that ``L = ℓₘₐₓ + 1`` here, and write:

> We adopt an equiangular sampling of the sphere with sample positions given by ``θ_t =
> \frac{π(2t+1)}{2L-1}``, where ``t ∈ \{0, 1, …, L-1\}`` […] and ``ϕ_p = \frac{2πp}{2L-1}``,
> where ``p ∈ \{0, 1, …, 2L-2\}``.

The band limit `ℓₘₐₓ` must be a non-negative integer.  The grid is defined for integer
indices only; functions of half-integer spin are sampled with
[`golden_ratio_spiral_pixels`](@ref), [`leja_pixels`](@ref) or [`sorted_ring_pixels`](@ref)
instead.

These are the ``L(2L-1)`` points returned, ordered with ``ϕ`` varying fastest.  The last
ring, ``t = L-1``, lies at the south pole ``θ = π``, and all ``2L-1`` of its points are
included, as distinct rotors that differ by a rotation about the pole; McEwen and Wiaux
count the pole once, for ``(L-1)(2L-1)+1`` samples.  Their algorithm also extends the ``θ``
domain to ``[0, 2π)``, reflecting the samples through the south pole to ``t ∈ \{L, …,
2L-2\}``, but those are not further sample positions on the sphere, and are not returned.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.  It must be an integer, like `ℓₘₐₓ`.
"""
@index_methods integer_only (
    "Functions of half-integer spin may be sampled with `golden_ratio_spiral_pixels`, "
    * "`leja_pixels` or `sorted_ring_pixels`."
) function mcewen_wiaux_pixels(s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T}
    check_equiangular_band_limit("McEwen–Wiaux", ℓₘₐₓ)
    let π = T(π), L = ℓₘₐₓ + 1
        # The ratio is formed first, so that it is exactly 1 on the last ring, which is then
        # exactly at the south pole rather than an ulp to either side of it.
        [
            @SVector [π * (T(2t+1) / T(2L - 1)), 2π*p / (2L - 1)]
            for t ∈ 0:(L - 1)
            for p ∈ 0:(2L - 2)
        ]
    end
end
@index_methods integer_only (
    "Functions of half-integer spin may be sampled with `golden_ratio_spiral_pixels`, "
    * "`leja_pixels` or `sorted_ring_pixels`."
) mcewen_wiaux_pixels(ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T} =
    mcewen_wiaux_pixels(0, ℓₘₐₓ, T)

@doc raw"""
    mcewen_wiaux_rotors([s], ℓₘₐₓ, [T=Float64])

Cover the sphere 𝕊² with pixels given by the [McEwenWiaux_2011](@citet) equiangular grid.

See [`mcewen_wiaux_pixels`](@ref) for more detailed explanation.  The quantity returned by
this function is a vector of `Rotor`s providing each pixel.

!!! note
    The `s` argument is not used in this function, but is included for consistency with
    other pixelization functions.
"""
@index_methods integer_only (
    "Functions of half-integer spin may be sampled with `golden_ratio_spiral_rotors`, "
    * "`leja_rotors` or `sorted_ring_rotors`."
) function mcewen_wiaux_rotors(s::IndexType, ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T}
    from_spherical_coordinates.(mcewen_wiaux_pixels(s, ℓₘₐₓ, T))
end
@index_methods integer_only (
    "Functions of half-integer spin may be sampled with `golden_ratio_spiral_rotors`, "
    * "`leja_rotors` or `sorted_ring_rotors`."
) mcewen_wiaux_rotors(ℓₘₐₓ::IndexType, ::Type{T}=Float64) where {T} =
    mcewen_wiaux_rotors(0, ℓₘₐₓ, T)
