name: Run benchmarks

# Disable this action for now; also see `if` below
on:
  push:
    branches-ignore:
      - '**'
# on: [pull_request]


jobs:
  Benchmark:
    runs-on: ubuntu-latest
    if: false # always skip job
    # if: >-
    #     !contains(github.event.head_commit.message, '[skip ci]')
    #     && !contains(github.event.head_commit.message, '[skip benchmark]')
    #     && !contains(github.event.head_commit.message, '[skip benchmarks]')
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6
      - name: Install dependencies
        run: julia -e 'using Pkg; pkg"add PkgBenchmark BenchmarkCI"'
      - name: Run benchmarks
        run: julia -e 'using BenchmarkCI; BenchmarkCI.judge(baseline="origin/main"); BenchmarkCI.displayjudgement()'
      - name: Post results
        run: julia -e 'using BenchmarkCI; BenchmarkCI.postjudge()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
