name: tests
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
  release:

env:
  JULIA_NUM_THREADS: auto

jobs:
  tests:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    if: >-
        !contains(github.ref, 'refs/tags/')
        && !contains(github.event.head_commit.message, '[skip ci]')
        && !contains(github.event.head_commit.message, '[skip tests]')
    strategy:
      matrix:
        version:
          - '1'
          #- 'nightly'
        os:
          - ubuntu-latest
        include:
          - os: windows-latest
            version: '1'
          - os: macOS-latest
            version: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          show-versioninfo: true
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v4
        if: "matrix.version == 'nightly' && matrix.os == 'ubuntu-latest'"
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
